# S3
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      bucket-full-url: ${S3_BUCKET_URL}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

# 테스트 DB
spring:
  datasource: # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/$dongpo?&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
  data: # redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret:
    dongpodongpodongpodongpodongpodginsadjkfhljihqwi123132